apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "AhedFinal.fullname" . }}
  labels:
    {{- include "AhedFinal.labels" . | nindent 4 }}
data:
  APP_MESSAGE: {{ .Values.config.APP_MESSAGE | quote }}
